app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
import json
from pickle import FALSE
from flask import Blueprint, request, jsonify
from helpers import user_token_required, library_token_required, secret_key_required
from models import db, User, Book, Library, book_schema, books_schema, library_schema, full_library_schema, libraries_schema, check_password_hash, login_schema

api = Blueprint('api',__name__, url_prefix='/api')


# Get User
@api.route('/users', methods = ['GET','POST'])
def user():
    try:
        if request.method == 'POST':
            email = request.json['email']
            password = request.json['password']
            print(1)
            user = User.query.filter(User.email == email).first()
            print(2)
            if user:
                if check_password_hash(user.password, password):
                    print(3)
                    response= login_schema.dump(user)
                    return response


    except:

        raise Exception('Invalid form data: Please check your form')
    

# PUT USER
@api.route('/user/<book_id>', methods=['PUT'])
@user_token_required
def add_user(current_user_token, book_id):
    book = Book.query.get(book_id)
    book.user_id = current_user_token.id
    book.in_stock = False
    
    db.session.commit()
    
    response = book_schema.dump(book)
    return jsonify(response)

# Routes for books 

# GET BOOK 

@api.route('/books', methods=['GET'])
def all_books():
    books = Book.query.filter_by(in_stock = True).all()
    response = books_schema.dump(books)
    return jsonify(response)
    

@api.route('/books/user/<id>', methods=['GET'])

def user_books(id):
    user = id
    books = Book.query.filter_by(user_id = user).all()
    response = books_schema.dump(books)
    return jsonify(response)

# POST
@api.route('/books', methods=['POST'])
@library_token_required
def create_book(current_library_token):
    title = request.json['book_title']
    isbn = request.json['isbn']
    pages = request.json['pages']
    genre = request.json['genre']
    author = request.json['author']
    token = current_library_token.library_token
 
    
    book = Book(title, isbn, pages, genre, author, token)
    
    db.session.add(book)
    db.session.commit()
    
    response = book_schema.dump(book)
    return jsonify(response)

# PUT
@api.route('/books/<id>', methods=['PUT'])
@library_token_required
def change_book(current_library_token, id):
    book = Book.query.get(id)
    book.book_title = request.json['book_title']
    book.isbn = request.json['isbn']
    book.page_amount = request.json['pages']
    book.genre = request.json['genre']
    book.author = request.json['author']
    if request.json['library_token']:
        book.token = request.json['library_token']

    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/books/checkout', methods=['PUT'])
@secret_key_required
def checkout_book(current_secret_key): 

    book = Book.query.filter_by(book_id = request.json['book_id']).first()
    book.in_stock = False
    book.user_id = request.json['user_id']

    db.session.commit()
    response = book_schema.dump(book)

    return jsonify(response)

@api.route('/books/checkin', methods=['PUT'])
@secret_key_required
def checkin_book(current_secret_key): 

    book = Book.query.filter_by(book_id = request.json['book_id']).first()
    book.in_stock = True
    book.user_id = ''

    db.session.commit()
    response = book_schema.dump(book)

    return jsonify(response)

# DELETE
@api.route('/books/<id>', methods = ['DELETE'])
@library_token_required
def delete_book(current_library_token, id):
    book = Book.query.get(id)
    db.session.delete(book)
    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)
    


# Library routes
# GET
@api.route('/library')
@secret_key_required
def libraries(current_secret_key):
    libraries = Library.query.all()
    response = libraries_schema.dump(libraries)
    return jsonify(response)

# POST
@api.route('/library', methods=['POST'])
@secret_key_required
def create_library(current_secret_key):
    name = request.json['library_name']
    email = request.json['library_email']
    address = request.json['library_address']
    city = request.json['library_city']
    state = request.json['library_state']
    password = request.json['library_password']
    
    library = Library(name, email, address, city, state, library_password=password)
    
    db.session.add(library)
    db.session.commit()
    
    response = full_library_schema.dump(library)
    return jsonify(response)

# PUT
@api.route('/library/<id>', methods=['PUT'])
@library_token_required
def change_library(current_library_token, id):
    library = Library.query.get(id)
    library.library_name = request.json['library_name']
    library.library_email = request.json['library_email']
    library.library_address = request.json['library_address']
    library.library_city = request.json['library_city']
    library.library_state = request.json['library_state']

    db.session.commit()
    
    response = full_library_schema.dump(library)
    return jsonify(response)

# DELETE
@api.route('/library/<id>', methods=['DELETE'])
@secret_key_required
def delete_library(current_secret_key, id):
    library = Library.query.get(id)
    db.session.delete(library)
    db.session.commit()
    
    response = library_schema.dump(library)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()



            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)





@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-sucess')
                return redirect(url_for('site.profile'))
            else:
                flash('You have failed in your attempt to access this content.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
@site.route('/home')
def home():    
    return render_template('index.html', title='Home')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/base.css">
<title>{{ title }}</title>
</head>
<body>
<nav class="navbar navbar-expand py-3 fixed-top">
    <div class="container">
        <h2 class="navbar-brand">Library</h2>
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{{ url_for('site.home') }}" class="nav-link">Home</a></li>
            {% if current_user.is_authenticated %}
            <li class="nav-item"><a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a></li>
            <li class="nav-item"><a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a></li>
            <li class="nav-item"><a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>